### ISSUE TITLE
Tool definition failed validation error when running createindex_singlevirus.cwl

### ISSUE THREAD

**Issue by jlee110** [yyoshiaki/VIRTUS#30]
ERROR Tool definition failed validation:
The CWL reference runner no longer supports pre CWL v1.0 documents. Supported versions are: 
v1.0
v1.1
v1.1.0-dev1 (with --enable-dev flag only)
v1.2
v1.2.0-dev1 (with --enable-dev flag only)
v1.2.0-dev2 (with --enable-dev flag only)
v1.2.0-dev3 (with --enable-dev flag only)
v1.2.0-dev4 (with --enable-dev flag only)
v1.2.0-dev5 (with --enable-dev flag only)

here's my cwltool:
Name: cwltool
Version: 3.1.20211004060744
Summary: Common workflow language reference implementation
Home-page: https://github.com/common-workflow-language/cwltool
Author: Common workflow language working group
Author-email: common-workflow-language@googlegroups.com
License: UNKNOWN
Location: /home/jlee110/anaconda3/lib/python3.8/site-packages
Requires: setuptools, rdflib, requests, coloredlogs, ruamel.yaml, psutil, schema-salad, prov, bagit, mypy-extensions, argcomplete, pydot, typing-extensions, shellescape
Required-by: cwlref-runner

**Comment by yyoshiaki** [comment]
Thank you for raising the issue. VIRTUS has been written by cwl v1.1 or v1.0, and I could not reproduce the error in my environment. Could you share the error and command in more detail?

**Comment by yyoshiaki** [comment]
I noticed another error occurred in the latest version of cwltool. Could you try older version of cwltool such as `3.1.20210922203925` ?

**Comment by jlee110** [comment]
Here's the command I'm using:

createindex_singlevirus.cwl --dir_name_STAR STAR_index_gi27 --runThreadN 12 --genomeFastaFiles /home/jlee110/VIRTUS-1.2.1/data/gi27/gi27.fasta --genomeSAindexNbases 3 --transcripts /home/jlee110/VIRTUS-1.2.1/data/gi27/gi27.transcripts.fasta --index_salmon salmon_index_gi27

I'll try an older version of cwltool.

**Comment by jlee110** [comment]
I just tried the 3.1.20210922203925 version of cwltool, unfortunately I got the same error. Will keep trying new things, and give you updates. Thank you for your replies.

**Comment by jlee110** [comment]
Could the cwl files be upgraded? I tried:

https://github.com/sbg/sevenbridges-cwl-draft2-upgrader

But it failed to convert some arguments.

**Comment by jlee110** [comment]
conda activate /home/jlee110/anaconda2
**I switched conda environment** and got a new error:

/home/jlee110/anaconda2/lib/python2.7/site-packages/cwltool/__init__.py:17: CWLToolDeprecationWarning: 
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020.
Please upgrade your Python as the Python 2.7 version of cwltool won't be
maintained after that date.

  """,  category=CWLToolDeprecationWarning)
Traceback (most recent call last):
  File "/home/jlee110/anaconda2/bin/cwl-runner", line 6, in <module>
    from cwltool.main import main
  File "/home/jlee110/anaconda2/lib/python2.7/site-packages/cwltool/main.py", line 35, in <module>
    from . import command_line_tool, workflow
  File "/home/jlee110/anaconda2/lib/python2.7/site-packages/cwltool/command_line_tool.py", line 36, in <module>
    from .context import LoadingContext  # pylint: disable=unused-import
  File "/home/jlee110/anaconda2/lib/python2.7/site-packages/cwltool/context.py", line 17, in <module>
    from .software_requirements import DependenciesConfiguration
  File "/home/jlee110/anaconda2/lib/python2.7/site-packages/cwltool/software_requirements.py", line 21, in <module>
    from galaxy.tool_util.deps.requirements import ToolRequirement, ToolRequirements
  File "/home/jlee110/anaconda2/lib/python2.7/site-packages/galaxy/tool_util/deps/__init__.py", line 160
    global_key = f"{config_prefix}_{key}"
                                        ^
SyntaxError: invalid syntax

**Comment by yyoshiaki** [comment]
Thank you for your struggle. 
VIRTUS is not written in sbg:draft-2, so you don't need perform sevenbrideges-cwl-draft2-upgrader.
I noticed you are using an old conda and python enviroment, which we havn't tested.
I'm not sure whether python2 is the main problem in this case, but we are actually testing in conda 4.10.1 and python 3.8.10.
So upgrading your python env might to be considered.

Another option is to check wheather cwltool runs proparly using some examples http://www.commonwl.org/user_guide/ .
If not, it would be an issure relating cwltool itself, so open an issue in cwl repo would be better.
