### ISSUE TITLE
TypeError: Passing a set as an indexer is not supported. Use a list instead.

### ISSUE THREAD

**Issue by patrick-douglas** [yyoshiaki/VIRTUS#35]
Dear @yyoshiaki 
I'm trying to run `VIRTUS_wrapper.py `, but I'm getting the following error, how can I fix it?
```
.....
    }
}INFO Final process status is success
Traceback (most recent call last):
  File "/home/me/VIRTUS2/bin//VIRTUS_wrapper.py", line 198, in <module>
    df_cov = df_cov.loc[list_index]
  File "/usr/local/lib/python3.10/dist-packages/pandas/core/indexing.py", line 1091, in __getitem__
    check_dict_or_set_indexers(key)
  File "/usr/local/lib/python3.10/dist-packages/pandas/core/indexing.py", line 2611, in check_dict_or_set_indexers
    raise TypeError(
TypeError: Passing a set as an indexer is not supported. Use a list instead.
```

All best
Patrick~

**Comment by patrick-douglas** [comment]
Sorry, my mistake the issue should be at VIRTUS2 repo
